[target.'cfg(all(target_arch = "arm", target_os = "none"))']
runner = "probe-run --chip RP2040"

[build]
target = "thumbv6m-none-eabi" # Cortex-M0 and Cortex-M0+

[env]
DEFMT_LOG = "debug"

[unstable]
build-std = ["core", "alloc"]
build-std-features = ["compiler-builtins-weak-intrinsics"]

[profile.dev]
debug = 2

[profile.dev.package.cortex-m-rt]
opt-level = 0

[profile.dev.package."*"]
opt-level = "z"

[profile.release]
opt-level = 3
debug = 2
